name: Check

on:
  pull_request:
    branches: [ main, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: check-kotlin-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [ detekt, ktlintCheck ]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up JDK 17
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: "temurin"
          java-version: 17
      - name: Check ${{ matrix.task }}
        run: ./gradlew ${{ matrix.task }}
